[package]
name = "MessageBoard"
version = "1.0.0"
authors = []

[addresses]
message_board_addr = "_"
vibe_social_addr = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", rev = "mainnet", subdir = "aptos-framework" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-framework.git", rev = "mainnet", subdir = "aptos-stdlib" }

[dev-dependencies]
