/**
 * Generate a new publisher key, set .env, then compile and publish.
 * Uses the CLI's sender address for compile (SDK and CLI derive addresses differently).
 *
 * Usage: npm run fresh-deploy
 * - Generates a new Ed25519 key, writes it and a placeholder address to .env
 * - Compiles, runs publish; if CLI reports a different sender, recompiles with that address and retries
 *
 * .env is not printed; key is never logged. Ensure .env is in .gitignore.
 */
require("dotenv").config();
const fs = require("node:fs");
const path = require("path");
const { spawnSync } = require("child_process");
const crypto = require("crypto");
const aptosSDK = require("@aptos-labs/ts-sdk");
const cli = require("@aptos-labs/ts-sdk/dist/common/cli/index.js");

const ROOT = path.join(__dirname, "../..");
const ENV_PATH = path.join(ROOT, ".env");

function setEnvInContent(envContent, name, value) {
  const regex = new RegExp(`^${name}=.*$`, "m");
  const line = `${name}=${value}`;
  if (envContent.match(regex)) {
    return envContent.replace(regex, line);
  }
  return envContent.trimEnd() + "\n" + line + "\n";
}

function writeEnv(envContent) {
  fs.writeFileSync(ENV_PATH, envContent, "utf8");
}

async function fundAddress(address, network) {
  if (network !== "devnet" && network !== "testnet") return;
  const faucetUrl =
    network === "devnet"
      ? "https://faucet.devnet.aptoslabs.com"
      : "https://faucet.testnet.aptoslabs.com";
  const fundUrl = `${faucetUrl}/mint?amount=100000000&address=${encodeURIComponent(address)}`;
  try {
    const res = await fetch(fundUrl, { method: "POST" });
    if (res.ok) console.log("Faucet: account funded.\n");
    else console.warn("Faucet response:", res.status, await res.text());
  } catch (e) {
    console.warn("Faucet failed:", e.message);
  }
}

function runPublish(privateKeyHex, address, network) {
  return spawnSync("node", [path.join(__dirname, "publish.js")], {
    cwd: ROOT,
    stdio: "pipe",
    shell: process.platform === "win32",
    encoding: "utf8",
    env: {
      ...process.env,
      VITE_MODULE_PUBLISHER_ACCOUNT_ADDRESS: address,
      VITE_MODULE_PUBLISHER_ACCOUNT_PRIVATE_KEY: privateKeyHex,
      VITE_APP_NETWORK: network,
      ASSUME_YES: "1",
    },
  });
}

function extractSenderFromError(output) {
  const match = output && output.match(/does not match the sender (0x[a-fA-F0-9]+)/);
  return match ? match[1] : null;
}

async function main() {
  const seed = crypto.randomBytes(32);
  const privateKeyHex = "0x" + seed.toString("hex");

  const Ed25519PrivateKey = aptosSDK.Ed25519PrivateKey;
  const Account = aptosSDK.Account;
  const privateKey = new Ed25519PrivateKey(seed);
  const account = Account.fromPrivateKey({ privateKey });
  const sdkAddress = account.accountAddress.toString();

  let envContent = "";
  if (fs.existsSync(ENV_PATH)) {
    envContent = fs.readFileSync(ENV_PATH, "utf8");
  } else {
    envContent = "# Generated by fresh-deploy\nVITE_APP_NETWORK=devnet\n";
  }
  const network = process.env.VITE_APP_NETWORK || "devnet";

  envContent = setEnvInContent(envContent, "VITE_MODULE_PUBLISHER_ACCOUNT_ADDRESS", sdkAddress);
  envContent = setEnvInContent(envContent, "VITE_MODULE_PUBLISHER_ACCOUNT_PRIVATE_KEY", privateKeyHex);
  envContent = setEnvInContent(envContent, "VITE_APP_NETWORK", network);
  writeEnv(envContent);

  console.log("New publisher key generated. Address (SDK):", sdkAddress);
  console.log("Updated .env (key not printed). Funding, compile, publish...\n");

  await fundAddress(sdkAddress, network);

  const move = new cli.Move();
  let addressToUse = sdkAddress;

  const doCompile = async (addr) => {
    await move.compile({
      packageDirectoryPath: path.join(ROOT, "contract"),
      namedAddresses: {
        message_board_addr: addr,
        vibe_social_addr: addr,
      },
    });
  };

  try {
    await doCompile(addressToUse);
  } catch (err) {
    console.error("Compile failed:", err.message);
    process.exit(1);
  }

  let result = runPublish(privateKeyHex, addressToUse, network);
  const out = (result.stdout || "") + (result.stderr || "");
  if (result.stdout) process.stdout.write(result.stdout);
  if (result.stderr) process.stderr.write(result.stderr);

  if (result.status !== 0 && out.includes("MODULE_ADDRESS_DOES_NOT_MATCH_SENDER")) {
    const cliSender = extractSenderFromError(out);
    if (cliSender && cliSender !== addressToUse) {
      console.log("\nUsing CLI sender address for compile:", cliSender);
      await fundAddress(cliSender, network);
      envContent = setEnvInContent(
        fs.readFileSync(ENV_PATH, "utf8"),
        "VITE_MODULE_PUBLISHER_ACCOUNT_ADDRESS",
        cliSender
      );
      writeEnv(envContent);
      try {
        await doCompile(cliSender);
      } catch (err) {
        console.error("Recompile failed:", err.message);
        process.exit(1);
      }
      result = runPublish(privateKeyHex, cliSender, network);
      if (result.stdout) process.stdout.write(result.stdout);
      if (result.stderr) process.stderr.write(result.stderr);
    }
  }

  process.exit(result.status === 0 ? 0 : result.status !== null ? result.status : 1);
}

main();
